# Generated by Django 3.2.25 on 2024-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20241017_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.png', null=True, upload_to='profilepictures'),
        ),
    ]
